### ISSUE TITLE
Evaluation of disk space will fail when device has already unmounted due to Hyper Backup Task

### ISSUE THREAD

**Issue by luddinho** [toafez/AutoPilot#12]
AutoPilot v1.1-100

There is a configuration option in Hyper Backup for USB devices to eject the disk after task has successfully finished.
 
![image](https://github.com/toafez/AutoPilot/assets/76713238/d4e62754-498d-4dff-9fea-cdb4e7ae7a66)

If this is checked, it could happen that the evaluation of the disk space will fail and report wrong information in the log.

e.g. In this case the expected report should be:
```
Speicherplatznutzung: 8.3 TB von 11 TB frei.
```

when device has been removed already from Hyper Backup the result is:
```
Speicherplatznutzung: 586 MB von 2.3 GB frei.
```
If the disk has been already unmounted the command `$(df -h "${mountpoint}")` will fetch the informatin of the mountpoint without active mount on this.

The idea is to determine the disk space only if the mount point still exists after script execution.
Proposal is available on local branch and PR for this issue will follow soon.

**Comment by toafez** [comment]
I would like to thank you once again for your really great bug fixes and system improvements. I have already accepted your PRs and if it continues like this, another release of AutoPilot will be coming soon.

toafez
