### ISSUE TITLE
Hyper Backup task could stuck when device is not ready at the moment when script triggers its execution

### ISSUE THREAD

**Issue by luddinho** [toafez/AutoPilot#13]
AutoPilot v1.1-100

In some rare situations it could happen that the triggered Hyper Backup task could stuck.
It seems to be a problem when firing HB tasks from the command line directly after a device has been mounted and the target is not ready.

After the [while loop](https://github.com/toafez/AutoPilot/blob/a35ffbb7509b209e41c6349ef920a4eff13595d7/ui/execute.sh#L130) to determine the mount point, the script is immediately invoked to start either a custom job or a predefined Hyper Backup task.

If the script starts a Hyper Backup task there is no check if the target is ready.

If this issue occurs, the following message will show in Hyper Backup task config from the GUI. But AutoPilot will finish successfully.

![image](https://github.com/toafez/AutoPilot/assets/76713238/2207e0b9-be77-4c19-88af-dbc194574b38)

The intermediate solution is to set an explicit wait time after the mount point has been determined to ensure the target is ready to start a Hyper Backup task.
Proposal is available on local branch and PR for this issue will follow soon.

**Comment by toafez** [comment]
I would like to thank you once again for your really great bug fixes and system improvements. I have already accepted your PRs and if it continues like this, another release of AutoPilot will be coming soon.

toafez
