### ISSUE TITLE
Internal disk is listed in menu of “External disks”

### ISSUE THREAD

**Issue by luddinho** [toafez/AutoPilot#18]
AutoPilot v1.1-300

On my system also the internal disk `/dev/mapper/cachedev_0` is listed with 3 shares of `/volume1` in menu “External disks”.
Please refer to the attached screenshot below.

![image](https://github.com/toafez/AutoPilot/assets/76713238/5ff99d45-9502-4e4b-af3f-b903cc74aad5)

**Comment by toafez** [comment]
Thanks for reporting. I have already localized and corrected the error. Please install version 1.1-400 and see if the bug has been fixed.

**Comment by luddinho** [comment]
Fix confirmed with 1.1-400.
