### ISSUE TITLE
Bereinigung läuft endlos - Festplatte wird nicht ausgeworfen

### ISSUE THREAD

**Issue by AllroundIT** [toafez/AutoPilot#23]
Hallo Tommes,
vielen Dank für deine Arbeit!

Ich habe leider Probleme, vllt. kannst du helfen. AutoPilot wird nicht fertig und wirft die externe USB Festplatte nicht aus.

Folgendes ist im Log zu sehen (nach Bereinigung läuft, geht es nicht weiter):

Sicherung wurde gestartet
Warte 30 Sekunden um sicherzugehen, dass das Sicherungsziel zur Verfügung steht
Suche maximal 30 Sekunden nach der Prozesskennung (PID) der Sicherung
Die Prozesskennung (PID) der Sicherung lautet: 12711
Sicherung abgeschlossen
Dauer der Sicherung: 0h:9m:21s

Suche maximal 30 Sekunden nach der Prozesskennung (PID) der Bereinigung
Die Prozesskennung (PID) der Bereinigung lautet: 24472
24492
Bereinigung läuft

**Comment by toafez** [comment]
Hi!

Das sollte weniger ein Problem von AutoPilot, sondern vielmehr ein Problem von Hyper Backup sein. Wirf mal einem Blick in die entsprechende Hyper Backup Aufgabe, sobald im AutoPilot Protokoll angezeigt wird, das die Bereinigung läuft. Sollten innerhalb Hyper Backup entsprechende Aktivitäten angezeigt werden, kann AutoPilot den externen Datenträger nicht auswerfen.

**Comment by toafez** [comment]
No more reply received
