### ISSUE TITLE
No possibility to confirm the deletion of the log via UI

### ISSUE THREAD

**Issue by luddinho** [toafez/AutoPilot#7]
Environement:
DSM 7.2.1
Autopilot 1.0-300

After hitting the button "Protokoll löschen" to clear the log the window for confirmation appears. But there is no possibility to confirm the decision.

![image](https://github.com/toafez/AutoPilot/assets/76713238/1ea1ced5-a82f-48ed-8c5c-b40290aa1d66)

**Comment by toafez** [comment]
This is really crazy because I noticed this error for the first time today. I am currently working on a major restructuring of the way AutoPilot localizes and executes scripts. This will further improve security. Therefore, it may take some time before this bug is fixed. But I am trying to hurry.

**Comment by toafez** [comment]
The bug was fixed in AutoPilot version 1.1-000. Thank you again for reporting the issue
